/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./src/**/*.{js,jsx,ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        // Agri-Culture System Colors
        surface: '#f7faf5',
        'surface-dim': '#d8dbd6',
        'surface-bright': '#f7faf5',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f1f4f0',
        'surface-container': '#ecefea',
        'surface-container-high': '#e6e9e4',
        'surface-container-highest': '#e0e3df',
        'on-surface': '#191c1a',
        'on-surface-variant': '#414844',
        'inverse-surface': '#2d312e',
        'inverse-on-surface': '#eff2ed',
        outline: '#717973',
        'outline-variant': '#c1c8c2',
        'surface-tint': '#3f6653',
        primary: '#012d1d',
        'on-primary': '#ffffff',
        'primary-container': '#1b4332',
        'on-primary-container': '#86af99',
        'inverse-primary': '#a5d0b9',
        secondary: '#516600',
        'on-secondary': '#ffffff',
        'secondary-container': '#c5f02e',
        'on-secondary-container': '#556a00',
        tertiary: '#262622',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#3c3c37',
        'on-tertiary-container': '#a8a6a0',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'primary-fixed': '#c1ecd4',
        'primary-fixed-dim': '#a5d0b9',
        'on-primary-fixed': '#002114',
        'on-primary-fixed-variant': '#274e3d',
        'secondary-fixed': '#c8f232',
        'secondary-fixed-dim': '#add500',
        'on-secondary-fixed': '#171e00',
        'on-secondary-fixed-variant': '#3d4d00',
        'tertiary-fixed': '#e5e2db',
        'tertiary-fixed-dim': '#c9c6c0',
        'on-tertiary-fixed': '#1c1c18',
        'on-tertiary-fixed-variant': '#474742',
        background: '#f7faf5',
        'on-background': '#191c1a',
        'surface-variant': '#e0e3df',
      },
      fontFamily: {
        display: ['Montserrat', 'sans-serif'],
        body: ['Manrope', 'sans-serif'],
      },
      borderRadius: {
        sm: '0.25rem',
        DEFAULT: '0.5rem',
        md: '0.75rem',
        lg: '1rem',
        xl: '1.5rem',
        full: '9999px',
      },
      spacing: {
        base: '8px',
        'container-max': '1280px',
        gutter: '24px',
        'margin-mobile': '16px',
        'margin-desktop': '40px',
        'section-gap': '80px',
        18: '72px',
      },
      maxWidth: {
        'container-max': '1280px',
      },
      boxShadow: {
        // Tonal Layers and Soft Ambient Depth (15% opacity of primary green #012d1d)
        'level-1': '0 4px 14px rgba(1, 45, 29, 0.15)',
        'level-2': '0 8px 24px rgba(1, 45, 29, 0.15)',
      },
    },
  },
  plugins: [],
}
